services:
  site:
    build: .
    volumes:
      - .:/site
      - jekyll_bundle:/usr/local/bundle
    ports:
      - "4000:4000"
      - "35729:35729"
    environment:
      - JEKYLL_ENV=development

volumes:
  jekyll_bundle: 